### ISSUE TITLE
Database cannot be written by the tdb writer

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#157]
The attached TDB can be read by pycalphad, but not written to TDB
[AlBeCuZrO.tdb.txt](https://github.com/pycalphad/pycalphad/files/1569257/AlBeCuZrO.tdb.txt)

To reproduce:

```python
from pycalphad import Database
dbf = Database.from_file('AlBeCuZrO.tdb.txt', fmt='tdb')
dbf.to_string(fmt='tdb')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brandon/Projects/pycalphad/pycalphad/io/database.py", line 346, in to_string
    self.to_file(result, **kwargs)
  File "/Users/brandon/Projects/pycalphad/pycalphad/io/database.py", line 318, in to_file
    format_registry[fmt].write(self, fname, **write_kwargs)
  File "/Users/brandon/Projects/pycalphad/pycalphad/io/tdb.py", line 820, in write_tdb
    parameters = sorted(param_sorted[subsystem])
  File "/Users/brandon/.virtualenvs/espei/lib/python3.5/site-packages/sympy/core/relational.py", line 195, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
```

**Comment by richardotis** [comment]
Will #161 resolve this?

**Comment by bocklund** [comment]
Looked at it again. For some reason it is just not wanting to pick up the ALO, ALO2, ALO2/3 species. Everything else seems to work fine.

**Comment by bocklund** [comment]
I have tracked down the issue, but I don't understand why I'm hitting it.

The problem is that when we parse parameters e.g. `PARAMETER G(LIQUID,SILICA;0) 298.15  0;       3000 N !` then we parse, process the parameter, and in `Database.add_parameter`, we hit `species_dict.get(s.upper(), Species(s))`. From what I can see, we should not be hitting `Species(s)`, but somehow having `Species(s)` ends up at

```python
class Species(object):
...
    def __new__(...):
        ...
        if isinstance(arg, str):
            parse_list = chemical_formula.parseString(arg.upper())
```

where we try to parse a chemical formula for what should be a Species name (e.g. `SI1O2` would work in the parameter, but the name does not). 

I tried to swap out the line 
```python
def add_parameter
...
            'constituent_array': tuple(tuple(species_dict.get(s.upper(), Species(s)) for s in xs) for xs in constituent_array),  # must be hashable type
...
```

And making the `Species(s)` -> `None` seems to work, even though `species_dict.get(s.upper(), None)` does not return `None`. So I don't understand why I'm hitting this issue. 

@richardotis can you reproduce this? 

I have a WIP test that you could use.

```python
def test_database_parameter_with_species_that_is_not_a_stoichiometric_formula():
    """Species names used in parameters do not have to be stoichiometric formulas"""

    # names are taken from the Thermo-Calc documentation set, Database Manager Guide, SPECIES

    tdb_string = """
     ELEMENT /-   ELECTRON_GAS              0.0000E+00  0.0000E+00  0.0000E+00!
     ELEMENT VA   VACUUM                    0.0000E+00  0.0000E+00  0.0000E+00!
     ELEMENT O    1/2_MOLE_O2(G)            0.0000E+00  0.0000E+00  0.0000E+00!
     ELEMENT SI   HCP_A3                    0.0000E+00  0.0000E+00  0.0000E+00!
     ELEMENT NA   HCP_A3                    0.0000E+00  0.0000E+00  0.0000E+00!
     ELEMENT SB   RHOMBOHEDRAL_A7           0.0000E+00  0.0000E+00  0.0000E+00!
     ELEMENT H    1/2_MOLE_H2(G)            0.0000E+00  0.0000E+00  0.0000E+00!

     SPECIES SILICA                      SI1O2 !  $ tests for arbitrary names
     SPECIES NASB_6OH                    NA1SB1O6H6 !  $ tests for underscores
     SPECIES SB-3                        SB/-3 !  $ tests for charge


     PHASE LIQUID:L %  1  1.0  !

     CONSTITUENT LIQUID:L : O, SI, NA, SB, H, SILICA, NASB_6OH, SB-3  :  !
     PARAMETER G(LIQUID,SB-3;0)        298.15  0;      3000 N !
     PARAMETER G(LIQUID,SILICA;0)      298.15  0;      3000 N !
     PARAMETER G(LIQUID,NASB_6OH;0)    298.15  0;      3000 N !

     """

    dbf = Database.from_string(tdb_string, fmt='tdb')

    species_names = [sp.name for sp in dbf.species]
    print(species_names)
    print(dbf._parameters.all())

    # check that the species are found
    assert 'SILICA' in species_names
    assert 'NASB_6OH' in species_names
    assert 'ALCL2OH.3WATER' in species_names
    assert 'SB-3' in species_names

    # TODO: test the parameters
```

**Comment by richardotis** [comment]
All the arguments to a function will get evaluated in Python before the arguments are passed to the function. I didn't consider that `Species(s)` might raise (e.g., by a species name not matching its chemical formula).

**Comment by richardotis** [comment]
See if 0941adb199afd4e5611576d2871d040e0323d44e fixes this problem.

**Comment by bocklund** [comment]
Duh. Should've realized. Just pushed the now passing test to the species-support branch.
