### ISSUE TITLE
equilibrium calculation with Dask not working

### ISSUE THREAD

**Issue by npaulson** [pycalphad/pycalphad#178]
I'm running into errors performing equilibrium calculations when providing a Dask scheduler

Here's my conda list output:
[conda_list.txt](https://github.com/pycalphad/pycalphad/files/2142724/conda_list.txt)

Here's the source code which reproduces the errors
[pycalphad_dask_2.py.txt](https://github.com/pycalphad/pycalphad/files/2142717/pycalphad_dask_2.py.txt)

Here's the tdb file
[cu-mg_dft.tdb.txt](https://github.com/pycalphad/pycalphad/files/2142718/cu-mg_dft.tdb.txt)

**Comment by bocklund** [comment]
Moving information from Gitter:

I haven't tried to reproduce it yet, but it seemed to be a serialization issue. It's unclear if it's related to dask 0.18 at this time.

Additionally, I would expect this to raise a deprecation warning in 0.18 even if successful, due to changing `scheduler`/`get` syntax in the `compute` call. This might be a good time to fix, test and bump the reqs.

**Comment by bocklund** [comment]
@r-williams-2 That might be related to some localization issues depending on where you are located. You could try forcing UTF8 by setting `PYTHONIOENCODING=UTF-8` as an environment variable (maybe see here: https://stackoverflow.com/questions/17096631/lookuperror-unknown-encoding-cp0)

**Comment by bocklund** [comment]
I have narrowed this down to not being able to serialize phase records using dask.

The following code 

1. Generates a phase record
2. triggers a serialization failure in dask's serialization function

We mainly need `serialize()` to work, however I can confirm that pickle and cloudpickle fail to serialize this as well. When this is solved, we should probably make this a test. 

```python


# minimal code to create a phase record
# borrowed from ESPEI and modified to return phase records rather than callables
import numpy as np
import sympy
from sympy import Symbol
from pycalphad import Model, variables as v
from pycalphad.core.sympydiff_utils import build_functions
from pycalphad.core.utils import unpack_kwarg, unpack_components
from pycalphad.core.phase_rec import PhaseRecord_from_cython
def get_pure_elements(dbf, comps):
    """
    Return a list of pure elements in the system

    Parameters
    ----------
    dbf : pycalphad.Database
        A Database object
    comps : list
        A list of component names (species and pure elements)

    Returns
    -------
    list
        A list of pure elements in the Database
    """
    comps = sorted(unpack_components(dbf, comps))
    components = [x for x in comps]
    desired_active_pure_elements = [list(x.constituents.keys()) for x in components]
    desired_active_pure_elements = [el.upper() for constituents in desired_active_pure_elements for el in constituents]
    pure_elements = sorted(set([x for x in desired_active_pure_elements if x != 'VA']))
    return pure_elements

def get_phase_records(dbf, comps, phases, model=None, param_symbols=None, output='GM', build_gradients=True):
    comps = sorted(unpack_components(dbf, comps))
    pure_elements = get_pure_elements(dbf, comps)
    eq_callables = {
        'massfuncs': {},
        'massgradfuncs': {},
        'callables': {},
        'grad_callables': {},
        'hess_callables': {},
    }

    models = unpack_kwarg(model, default_arg=Model)
    param_symbols = param_symbols if param_symbols is not None else []
    # wrap param symbols in Symbols if they are strings
    if all([isinstance(sym, string_types) for sym in param_symbols]):
        param_symbols = [Symbol(sym) for sym in param_symbols]
    param_values = np.zeros_like(param_symbols, dtype=np.float64)

    phase_records = {}
    # create models
    # starting from pycalphad
    for name in phases:
        mod = models[name]
        if isinstance(mod, type):
            models[name] = mod = mod(dbf, comps, name)
        site_fracs = mod.site_fractions
        variables = sorted(site_fracs, key=str)
        try:
            out = getattr(mod, output)
        except AttributeError:
            raise AttributeError('Missing Model attribute {0} specified for {1}'
                                 .format(output, mod.__class__))

        # Build the callables of the output
        # Only force undefineds to zero if we're not overriding them
        undefs = list(out.atoms(Symbol) - out.atoms(v.StateVariable) - set(param_symbols))
        for undef in undefs:
            out = out.xreplace({undef: float(0)})
        build_output = build_functions(out, tuple([v.P, v.T] + site_fracs), parameters=param_symbols, include_grad=build_gradients)
        if build_gradients:
            cf, gf = build_output
        else:
            cf = build_output
            gf = None
        hf = None
        eq_callables['callables'][name] = cf
        eq_callables['grad_callables'][name] = gf
        eq_callables['hess_callables'][name] = hf

        # Build the callables for mass
        # TODO: In principle, we should also check for undefs in mod.moles()

        if build_gradients:
            mcf, mgf = zip(*[build_functions(mod.moles(el), [v.P, v.T] + variables,
                                           include_obj=True,
                                           include_grad=build_gradients,
                                           parameters=param_symbols)
                           for el in pure_elements])
        else:
            mcf = tuple([build_functions(mod.moles(el), [v.P, v.T] + variables,
                                           include_obj=True,
                                           include_grad=build_gradients,
                                           parameters=param_symbols)
                           for el in pure_elements])
            mgf = None
        eq_callables['massfuncs'][name] = mcf
        eq_callables['massgradfuncs'][name] = mgf

        # creating the phase records triggers the compile
        phase_records[name.upper()] = PhaseRecord_from_cython(comps, variables,
                                                           np.array(dbf.phases[name].sublattices, dtype=np.float),
                                                           param_values, eq_callables['callables'][name],
                                                           eq_callables['grad_callables'][name], eq_callables['hess_callables'][name],
                                                           eq_callables['massfuncs'][name], eq_callables['massgradfuncs'][name])

    # finally, add the models to the eq_callables
    eq_callables['model'] = dict(models)
    return phase_records

from pycalphad import Database
from distributed.protocol.serialize import serialize

if __name__ == '__main__':

    comps = ['CU', 'VA']
    phases = ['FCC_A1']

    dbf = Database('/Users/brandon/Projects/espei-runs/CU-MG/CU-MG_mcmc.tdb')
    print('creating phase records')
    mod = Model(dbf, ['CU', 'VA'], 'FCC_A1')
    phase_records = get_phase_records(dbf, comps, phases, build_gradients=False)
    prx = phase_records['FCC_A1']
    print('serializing phase records')
    serialization_result = serialize(prx)
    # if fails, returns a tuple where {'serializer': 'error'} is the first value.
    print('dask.protocol.serialize.serialize() result: {}'.format(serialization_result))
```

This outputs the following:

```python
dask.protocol.serialize.serialize() result: ({'serializer': 'error'}, [b'Could not serialize object of type PhaseRecord', b'Traceback (most recent call last):\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 38, in dumps\n    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)\n  File "stringsource", line 2, in View.MemoryView._memoryviewslice.__reduce_cython__\nTypeError: no default __reduce__ due to non-trivial __cinit__\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 196, in serialize\n    header, frames = dumps(x)\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 54, in pickle_dumps\n    return {\'serializer\': \'pickle\'}, [pickle.dumps(x)]\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 51, in dumps\n    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 900, in dumps\n    cp.dump(obj)\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 234, in dump\n    return Pickler.dump(self, obj)\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/pickle.py", line 409, in dump\n    self.save(obj)\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/pickle.py", line 521, in save\n    self.save_reduce(obj=obj, *rv)\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 768, in save_reduce\n    save(args)\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/pickle.py", line 476, in save\n    f(self, obj) # Call unbound method with explicit self\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/pickle.py", line 751, in save_tuple\n    save(element)\n  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/pickle.py", line 496, in save\n    rv = reduce(self.proto)\n  File "stringsource", line 2, in View.MemoryView._memoryviewslice.__reduce_cython__\nTypeError: no default __reduce__ due to non-trivial __cinit__\n'])
```

Posting this as an update, but I'm still working on a solution.

As an aside: writing a test for this is also some motivation to factor out building phase records and callables in calculate and equilibrium (and removing it from ESPEI as well).

**Comment by bocklund** [comment]
I don’t know why we don’t hit this issue with ESPEI

**Comment by richardotis** [comment]
Pickling a PhaseRecord is controlled by this function:

```python
cdef public class PhaseRecord(object)[type PhaseRecordType, object PhaseRecordObject]:
    """
    This object exposes a common API to the solver so it doesn't need to know about the differences
    between Model and CompiledModel. Each PhaseRecord holds a reference to its own Model or CompiledModel;
    these objects are pickleable. PhaseRecords are immutable after initialization.
    """
    def __reduce__(self):
            return PhaseRecord_from_cython_pickle, (self.variables, self.phase_dof, self.sublattice_dof,
                                                  self.parameters, self.num_sites, self.composition_matrices,
                                                  self.vacancy_index, self._ofunc, self._gfunc, self._hfunc)
```

The error you're getting looks like a failure to pickle one of the arguments (a memoryview). Maybe wrapping the memoryviews in `__reduce__` with calls to `np.array` will fix it?

**Comment by bocklund** [comment]
Thanks. I’ll look into this tomorrow. 

I also realized this doesn’t happen in ESPEI because we don’t send the phase records over the wire, only the callables. Phase records get reconstituted in the equilibrium and calculate calls.

**Comment by bocklund** [comment]
Code in `__reduce__` was written before Species. I'm not sure, but it looks like to be able to reconstitute the mass objective and gradient we need to know some of the pure elements info. 

To me, it looks like reduce was just skipping some of the init function. Is that an optimization we need, or can we just run through `__init__` again? We might have to set the initial input arguments as attributes of the PhaseRecord class, but as long as it's not a memory or performance issue, I think it should reduce the amount of code by making the `PhaseRecord_from_cython_pickle` redundant (we can just use the regular phase record initializer).

**Comment by r-williams-2** [comment]
@bocklund Changing encoding to UTF-8 worked a treat. Cheers for that!

**Comment by bocklund** [comment]
This is the minimal code to reproduce this error on the current develop branch with `build_callables`:


```python
import cloudpickle
from pycalphad import Database
from pycalphad.codegen.callables import build_callables


CU_MG_TDB_LIQUID = """
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

ELEMENT CU BLANK 0 0 0 !
ELEMENT MG BLANK 0 0 0 !
ELEMENT VA BLANK 0 0 0 !


FUNCTION GHSERCU 298.15 1.29223E-7*T**3 - 0.00265684*T**2 - 24.112392*T*LN(T)
   + 130.485235*T - 7770.458 + 52478*T**(-1); 1357.77 Y -31.38*T*LN(T) +
   183.803828*T - 13542.026 + 3.64167E+29*T**(-9); 3200.0 N !
FUNCTION GHSERMG 298.15 -1.393669E-6*T**3 + 0.0004858*T**2 -
   26.1849782*T*LN(T) + 143.675547*T - 8367.34 + 78950*T**(-1); 923.0 Y
   -34.3088*T*LN(T) + 204.716215*T - 14130.185 + 1.038192E+28*T**(-9); 3000.0
   N !
FUNCTION GHSERVA 1 0; 10000 N !
FUNCTION GLIQCU 298.15 -5.8489E-21*T**7 - 9.511904*T + GHSERCU# + 12964.735;
   1357.77 Y -31.38*T*LN(T) + 173.881484*T - 46.545; 3200.0 N !
FUNCTION GLIQMG 298.15 -8.0176E-20*T**7 - 8.83693*T + GHSERMG# + 8202.243;
   923.0 Y -34.3088*T*LN(T) + 195.324057*T - 5439.869; 3000.0 N !
FUNCTION VV0012 1 14321.1; 10000 N !
FUNCTION VV0013 1 -4923.18; 10000 N !
FUNCTION VV0014 1 -1962.8; 10000 N !
FUNCTION VV0015 1 -31626.6; 10000 N !


TYPE_DEFINITION % SEQ * !
DEFINE_SYSTEM_DEFAULT ELEMENT 2 !
DEFAULT_COMMAND DEFINE_SYSTEM_ELEMENT VA !

PHASE LIQUID %  1 1 !
CONSTITUENT LIQUID :CU,MG: !

PARAMETER G(LIQUID,CU;0) 1 GLIQCU#; 10000 N !
PARAMETER G(LIQUID,MG;0) 1 GLIQMG#; 10000 N !
PARAMETER L(LIQUID,CU,MG;0) 1 VV0015#; 10000 N !
PARAMETER L(LIQUID,CU,MG;1) 1 VV0014#; 10000 N !
PARAMETER L(LIQUID,CU,MG;2) 1 VV0013#; 10000 N !
PARAMETER L(LIQUID,CU,MG;3) 1 VV0012#; 10000 N !

"""

if __name__ == '__main__':

    dbf = Database.from_string(CU_MG_TDB_LIQUID, fmt='tdb')
    comps = ['CU', 'MG', 'VA']
    phases = ['LIQUID']


    callables = build_callables(dbf, comps, phases)

    prx = callables['phase_records']['LIQUID']
    cloudpickle.dumps(prx)
```

**Comment by richardotis** [comment]
@bocklund Thanks, the minimal example made tracking down the bug very easy.

**Comment by bocklund** [comment]
With the changes in #196, this works now. To use distributed Clients for scheduling, one instantiates a `distributed.Client` and passes `scheduler=distributed`:

```python
from pycalphad import Database, equilibrium, variables as v
from dask.distributed import Client


if __name__ == '__main__':
    # this acts like a global variable in the sense that you don't have to pass it
    # however, this it will not work if you don't instantiate it
    scheduler = Client()

    comps = ['CU', 'MG', 'VA']
    phases = ['LIQUID', 'FCC_A1', 'HCP_A3', 'CUMG2', 'LAVES_C15']
    conds = {v.P: 101325, v.T: (300, 1500, 20), v.X('MG'): (0, 1, 0.05)}

    dbf = Database('cu-mg_dft.tdb')

    eq_result = equilibrium(dbf, comps, phases, conds, scheduler="distributed")
    print(eq_result)
```

This gave a speedup of a little above 4x for my computer.

Note that you can also pass either `sync`, `threads`, `processes` to `scheduler` without the distributed `Client`, however I didn't see much performance improvement for `threads` or `processes` over `sync` in a test where I would expect `processes` to be better. I think this is related to #101
