### ISSUE TITLE
Regression on pyparsing 2.1.0

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#38]
Database loading appears to hang on pyparsing 2.1.0.

Reporting user traceback:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pycalphad/io/database.py", line 110, in __new__
    return cls.from_file(fname, fmt=fmt)
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pycalphad/io/database.py", line 183, in from_file
    format_registry[fmt.lower()].read(dbf, fd)
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pycalphad/io/tdb.py", line 747, in read_tdb
    tokens = _tdb_grammar().parseString(command)
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1152, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1083, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1018, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 2554, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1083, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1018, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 2440, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1083, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1018, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 2695, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1083, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1018, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 2423, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1083, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1018, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 2695, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1083, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1018, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 2625, in parseImpl
    if e.canParseNext(instring, tmpLoc):
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1066, in canParseNext
    self.tryParse(instring, loc)
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1060, in tryParse
    return self._parse( instring, loc, doActions=False )[0]
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 1080, in _parseCache
    return (value[0],value[1].copy())
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 548, in copy
    ret = ParseResults( self.__toklist )
  File "/Users/firebird/allPythonEnv/pycalphad031/lib/python2.7/site-packages/pyparsing.py", line 285, in __init__
    self.__asList = asList
KeyboardInterrupt
```

**Comment by richardotis** [comment]
I can reproduce this error on Python 2.7 and 3.5 with pyparsing 2.1.0. Downgrading to 2.0.7 makes the problem disappear.

**Comment by richardotis** [comment]
Issue reported upstream https://sourceforge.net/p/pyparsing/bugs/91/

**Comment by richardotis** [comment]
https://sourceforge.net/p/pyparsing/bugs/92/ is the new issue tracking the bug -- upstream is reporting it's fixed in master.

**Comment by richardotis** [comment]
pyparsing 2.1.1 has been released. Once this issue is confirmed fixed, we'll bump the version in setup.py

**Comment by richardotis** [comment]
pyparsing 2.1.1 seems to have a different regression, so we're just going to stay on 2.0.7 for the near future.

**Comment by richardotis** [comment]
a7be84a should have fixed this for all recent versions of pyparsing.
