### ISSUE TITLE
StateVariable.__getitem__ implementation causes infinite loop when used in SymEngine matrix classes

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#547]
This code produces an infinite loop:
```python
from pycalphad import variables as v
from symengine import ImmutableDenseMatrix
print("X SV")
ImmutableDenseMatrix([v.StateVariable("X")])
print('done')
```

I traced it back to the implementation of `StateVariable.__getitem__`. Applying a patch like this fixes it:
```patch
diff --git a/pycalphad/variables.py b/pycalphad/variables.py
index 5b04dfd3..09b77ee6 100644
--- a/pycalphad/variables.py
+++ b/pycalphad/variables.py
@@ -215,7 +215,7 @@ class StateVariable(Symbol):
     def __hash__(self):
         return hash((self.__class__, self.name))
 
-    def __getitem__(self, new_units: str) -> "StateVariable":
+    def with_new_units(self, new_units: str) -> "StateVariable":
         "Get StateVariable with different display units"
         newobj = copy(self)
         newobj.display_units = new_units
```

I'm not exactly sure where along the line it's getting messed up. The method resolution order doesn't contain any objects that have `__getitem__` defined.
```python
from pycalphad import variables as v
v.StateVariable.mro()
```

gives:
```
[pycalphad.variables.StateVariable,
 symengine.lib.symengine_wrapper.Symbol,
 symengine.lib.symengine_wrapper.Expr,
 symengine.lib.symengine_wrapper.Basic,
 object]
```

```
X SV
Traceback (most recent call last):
  File "/Users/bocklund1/src/calphad/issue-xxx-leak/matrix_leak.py", line 4, in <module>
    ImmutableDenseMatrix([v.StateVariable("X")])
  File "symengine_wrapper.pyx", line 3378, in symengine.lib.symengine_wrapper.DenseMatrixBase.__cinit__
  File "/Users/bocklund1/src/calphad/pycalphad/pycalphad/variables.py", line 219, in __getitem__
    raise ValueError()
ValueError
```
(this traceback is on SymEngine 0.11, line 3378 is https://github.com/symengine/symengine.py/blob/b0f15af6db3c8e297cc59620c80e056d6e94f41e/symengine/lib/symengine_wrapper.in.pyx#L3378)

My guess is that this is somehow conflicting with the implementation of `DenseMatrixBase.__getitem__` and creates some infinite loop when `new symengine.DenseMatrix` is called. `DenseMatrixBase` and `_DictBasic` are the only classes implementing `__getitem__`) but I'm not sure how that's called when we pass in a `StateVariable`.

**Comment by bocklund** [comment]
The main question for now is whether to try to raise this upstream in SymEngine, try to fix locally, or to change the `__getitem__` API for getting new units for state variables

**Comment by richardotis** [comment]
I like the `__getitem__` syntactic sugar, but it may turn out to integrate poorly with the rest of SymEngine. My suggestion would be:
1. Report the issue upstream.
2. Rename the function to `StateVariable.with_units(...)` and update the documentation and examples accordingly.
3. We could always reintroduce `__getitem__` as an alias later once the issue is fixed.
