### ISSUE TITLE
Oxygen Partial Pressure-Oxide Phase Fraction plotting and condition support

### ISSUE THREAD

**Issue by CountryTree3** [pycalphad/pycalphad#586]
May I ask you if there is any way for pycalphad to calculate the Oxygen Partial Pressure-Oxide Phase Fraction diagram?
A calculation result from Pandat software is shown in the picture.
![20241218192424](https://github.com/user-attachments/assets/6fcead13-18f2-4052-8ef3-1ddb597b2db1)

**Comment by richardotis** [comment]
There's no built-in partial pressure property yet, but you should be able to perform a calculation over a range of fixed oxygen chemical potentials (relative to the reference), and then transform the axis afterward.

**Comment by CountryTree3** [comment]
> There's no built-in partial pressure property yet, but you should be able to perform a calculation over a range of fixed oxygen chemical potentials (relative to the reference), and then transform the axis afterward.
  Sincerely thank you for your patient answer. I am now able to use PyCalphad to calculate Zr-O binary ceramic system and have achieved good consistency with Pandat and Thermo Calc software.
  However, when I calculate the Zr-B-O ternary ceramic, Pycalphad will return an error: "ZeroDivisionError: float division" from the equilibrium function. The source code and error message are displayed as follows. If you could spare a moment to offer some advice on debugging code, I would be immensely grateful.
```
# Reading TDB
dbf = Database("user.TDB")
compsss = ['ZR', 'B', 'O', 'VA']
phases = ['GAS', 'LIQUID', 'IONIC_LIQUID', 'B2ZR', 'ZRO2_MONO', 'ZRO2_TETR', 'ZRO2_CUB', 'BETA_RHOMBO_B']

# Oxygen activity
Oxy_min = 10**(-30)
Oxy_max = 10**(0)

intervals = 100
acr_O = np.arange(Oxy_min, Oxy_max, (Oxy_max-Oxy_min)/intervals)

# Calculate reference state and chemical potential of component Oxy
CURRENT_T = 2273
ref_eq = equilibrium(dbf, ['O'], 'GAS', {v.P: 101325, v.T: CURRENT_T})
chempot_ref = ref_eq.MU.sel(component='O').squeeze().values.tolist()
chempot_O = chempot_ref + (8.314*CURRENT_T) * np.log(acr_O)

# Stepping by v.MU('O')
### ZeroDivisionError: float division
eq = equilibrium(dbf, compsss, phases, \
    {v.P: 101325, v.T: CURRENT_T, v.X('B'):0.6666667, v.N:1, \
     v.MU('O'): (np.min(chempot_O), np.max(chempot_O), (max(chempot_O)-min(chempot_O))/intervals)})

# Oxygen activity transition 
MU = eq.MU.sel(component='O').squeeze().values.tolist()
acrO_corrspeding_MU = np.exp((eq.MU.sel(component='O').squeeze().values - chempot_ref) / (8.314*CURRENT_T))

# Oxygen partial pressure calculation
lnacr_O2_GAS = np.log10((np.array(acrO_corrspeding_MU))**2)
```
Error message:
```
Traceback (most recent call last):
  File "C:\Users\Desktop\Origin_code\pycalphad\test_arcO.py", line 118, in <module>
    eq = equilibrium(dbf, compsss, phases, \
  File "C:\Users\Desktop\Origin_code\pycalphad\pycalphad\core\equilibrium.py", line 70, in equilibrium
    properties = wks.eq
  File "C:\Users\Desktop\Origin_code\pycalphad\pycalphad\core\workspace.py", line 282, in __get__
    default_value = obj.recompute()
  File "C:\Users\Desktop\Origin_code\pycalphad\pycalphad\core\workspace.py", line 363, in recompute
    return _solve_eq_at_conditions(properties, self.phase_record_factory, grid,
  File "pycalphad\\core\\eqsolver.pyx", line 242, in pycalphad.core.eqsolver._solve_eq_at_conditions
    result = iter_solver.solve(composition_sets, cur_conds)
  File "C:\Users\Desktop\Origin_code\pycalphad\pycalphad\core\solver.py", line 164, in solve
    converged = spec.run_loop(state, 1000)
  File "pycalphad\\core\\minimizer.pyx", line 394, in pycalphad.core.minimizer.SystemSpecification.run_loop
    cpdef bint run_loop(self, SystemState state, int max_iterations):
  File "pycalphad\\core\\minimizer.pyx", line 403, in pycalphad.core.minimizer.SystemSpecification.run_loop
    eq_soln = solve_state(self, state)
  File "pycalphad\\core\\minimizer.pyx", line 833, in pycalphad.core.minimizer.solve_state
    equilibrium_matrix, equilibrium_soln = construct_equilibrium_system(spec, state, 0)
  File "pycalphad\\core\\minimizer.pyx", line 684, in pycalphad.core.minimizer.construct_equilibrium_system
    fill_equilibrium_system(equilibrium_matrix, equilibrium_rhs, spec, state)
  File "pycalphad\\core\\minimizer.pyx", line 268, in pycalphad.core.minimizer.fill_equilibrium_system
    write_row_fixed_mole_fraction(equilibrium_matrix[component_row_offset + fixed_molefrac_cond_idx, :],
  File "pycalphad\\core\\minimizer.pyx", line 145, in pycalphad.core.minimizer.write_row_fixed_mole_fraction
    (phase_amt[idx]/current_system_amount) * mass_jac[component_idx, num_statevars+j] * c_component[chempot_idx, j]
ZeroDivisionError: float division
```

**Comment by bocklund** [comment]
@CountryTree3 following up on whether this works with the newly released pycalphad 0.11.2?

**Comment by CountryTree3** [comment]
@bocklund I obtained results that are consistent with those from Pandat. I think that the newly released pycalphad 0.11.2 works perfectly resolved the above issue I was encountering.
Thank you so much for your continued work and updates on pycalphad !

<img width="715" height="533" alt="Image" src="https://github.com/user-attachments/assets/c16bc00a-792a-469e-8806-c8beb7629105" />

**Comment by bocklund** [comment]
Excellent! Thanks for quickly checking. Closing this.
